spring.application.name=EnServ

spring.datasource.url=jdbc:postgresql://localhost:5432/chipin
spring.datasource.username=chipin
spring.datasource.password=chipin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
